option to make more pawnshop locations
qbcore-framework/qb-pawnshop pull request #37
Opened 2022-06-22 20:08 UTC by mjvanhaastert

Added the option to you can make more then 1 pawnshop location.
Also fixed the fxmanifest.lua as the '@oxmysql/lib/MySQL.lua' was not in there so the ban exploit feature wasnt working

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-06-22 20:44 UTC, FjamZoo approved these changes

2022-06-22 21:03 UTC, tom-osborne commented
@mjvanhaastert needs the config file update also. Then I think we are good.

2022-06-22 21:55 UTC, tom-osborne requested changes
Just a couple of tweaks please @mjvanhaastert - Thanks!

2022-06-22 21:55 UTC, tom-osborne commented on client/main.lua
> +        local pawnShopCombo = ComboZone:Create({ zone }, { name = 'NewPawnShopCombo', debugPoly = false })
`zone` is already a table, so this line needs to change to: 
`local pawnShopCombo = ComboZone:Create(zone, { name = 'NewPawnShopCombo', debugPoly = false })`

2022-06-22 21:55 UTC, tom-osborne commented on fxmanifest.lua
> +server_script {
Change this line to `server_scripts {` please (plural)

2022-06-23 18:52 UTC, tom-osborne approved these changes
Changes approved. Thanks!

2022-06-23 18:53 UTC, merged