Fix for Pawnshop Exploit
qbcore-framework/qb-pawnshop pull request #45
Opened 2022-11-20 22:49 UTC by Bama94

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? YES
- Does your code fit the style guidelines? YES
- Does your PR fit the contribution guidelines? YES

2022-11-20 23:04 UTC, Irishstevie reviewed
Remove white Space

2022-11-20 23:08 UTC, Bama94 commented on server/main.lua
> +                --TriggerClientEvent('qb-pawnshop:client:openMenu', src)
I had left it there, not thinking about the fact that github shows what was removed lol

2022-11-20 23:09 UTC, Bama94 commented
Done

2022-11-21 11:06 UTC, charj commented on server/main.lua
> -                return
Have we intentionally removed the `return`?

2022-11-21 11:07 UTC, charj commented on server/main.lua
> +                TriggerClientEvent('QBCore:Notify', src, 'Inventory Was too full to recieve all possible items. Try making sure your inventory isn\'t full next time. Items Lost: '..QBCore.Shared.Item
Would it be better to store this string in Locales so that it can be translated?

2022-11-21 11:07 UTC, charj commented on server/main.lua
> +                TriggerClientEvent('QBCore:Notify', src, 'Inventory Was too full to recieve all possible items. Try making sure your inventory isn\'t full next time. Items Lost: '..QBCore.Shared.Item
`recieve` needs to be `receive`

2022-11-21 11:08 UTC, charj commented on server/main.lua
> +                TriggerClientEvent('QBCore:Notify', src, 'Inventory Was too full to recieve all possible items. Try making sure your inventory isn\'t full next time. Items Lost: '..QBCore.Shared.Item
`I` before `E` except after `C`

2022-11-21 22:26 UTC, GodyFromDiscord requested changes

2022-11-21 22:26 UTC, GodyFromDiscord commented on server/main.lua
> +                TriggerClientEvent('QBCore:Notify', src, 'Inventory Was too full to recieve all possible items. Try making sure your inventory isn\'t full next time. Items Lost: '..QBCore.Shared.Item
"Inventory Was" should also just be "Inventory was"

2022-11-21 23:43 UTC, Bama94 commented
Removed the was and changed the recieve to receive and moved it to a locale, but english is the only one I know soooo.....

2022-11-21 23:48 UTC, Bama94 commented on server/main.lua
> -                return
I didn't test it with it as the return would send it back to the beginning of this code but I will try it as soon as I can since FiveM is down

2022-11-21 23:51 UTC, Bama94 commented on server/main.lua
> -                return
But currently without the `return` it takes you back to the original menu without the `Pick Up Melted Items` and you just loose the items you could of got because of your inventory being full

2022-11-22 16:10 UTC, Manason commented on locales/en.lua
> +        inventory_full = 'Inventory too full to receive all possible items. Try making sure inventory isn\'t full next time. Items Lost: %{value}'
```suggestion
        inventory_full = 'Inventory full. Items Lost: %{value}'

```

2022-11-22 19:26 UTC, Bama94 commented on locales/en.lua
> +        inventory_full = 'Inventory too full to receive all possible items. Try making sure inventory isn\'t full next time. Items Lost: %{value}'
I mean, you got a point, but at the end of the day, atleast it's there and can be adjusted

2022-11-22 20:39 UTC, charj commented on locales/en.lua
> +        inventory_full = 'Inventory too full to receive all possible items. Try making sure inventory isn\'t full next time. Items Lost: %{value}'
This is true, I'm happy either way

2022-11-22 23:38 UTC, SMVampire commented
Seems people are more interested in nitpicking sentence structure and best practice variable naming than prioritizing pushing an **exploit fix** and fixing the minor details later

2022-11-22 23:41 UTC, SMVampire approved these changes
Just merge it, it's an exploit fix

2022-11-23 07:48 UTC, Manason approved these changes

2022-11-23 16:41 UTC, Irishstevie approved these changes
This fixes the issue we can fix the lang later

2022-11-23 18:52 UTC, charj approved these changes
LGTM

2022-11-23 19:36 UTC, KamuiKody approved these changes
have tested this works fine for me

2022-11-23 19:37 UTC, KamuiKody approved these changes

2022-11-23 19:42 UTC, merged